name: Dispatch Release & Artifact
on:
  schedule:
    - cron: '0 0 * * 1' # Runs at 00:00 UTC every Monday
  workflow_dispatch:
    inputs:
      desc:
        description: "Enter a custom description for the release"
        required: false
        default: "Weekly release"

permissions:
  contents: write
  models: read

jobs:
  weekly-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up date variables
        id: dates
        run: |
          TODAY=$(date -u +"%Y-%m-%d")
          NOW=$(date -u +"%H.%M.%S")
          LAST_WEEK=$(date -u -d "last monday -7 days" +"%Y-%m-%d")
          echo "today=$TODAY" >> $GITHUB_OUTPUT
          echo "now=$NOW" >> $GITHUB_OUTPUT
          echo "lastweek=$LAST_WEEK" >> $GITHUB_OUTPUT

      - name: Get commits from past week
        id: commits
        run: |
          git fetch --prune --unshallow || true
          COMMITS=$(git log --since="${{ steps.dates.outputs.lastweek }}T00:00:00Z" --until="${{ steps.dates.outputs.today }}T00:00:00Z" --pretty=format:"%h %s" --no-merges)
          echo "$COMMITS"
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: minify js to paste in console
        uses: jossydevers/minify-js@v1.0.0
        with:
          directory: 'vav4inject.js' 
          output: 'minify/' 

      - name: Read minified JS for pasting
        id: paste_js
        run: |
          # Read the entire content of minify/paste.js and escape backticks for Markdown code block safety
          PASTE_CONTENT=$(cat minify/vav4inject.min.js | sed 's/`/\\`/g')
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$PASTE_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload as GitHub Artifact
        if: steps.release_files.outputs.files != ''
        uses: actions/upload-artifact@v4
        with:
          name: weekly-release-assets
          path: |
            minify/vav4inject.min.js
            tampermonkey.js
            vav4inject.js

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: weekly-${{ steps.dates.outputs.today }}-time-${{ steps.dates.outputs.now }}
          name: weekly-${{ steps.dates.outputs.today }} at time [${{ steps.dates.outputs.now }}]
          body: |
            ${{ github.event.inputs.desc }}
            ---
            ## Paste in Console (minified)
            ```
            ${{ steps.paste_js.outputs.content }}
            ```
          files: |
            minify/vav4inject.min.js
            tampermonkey.js
            vav4inject.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
